CREATE DATABASE agenda;

USE agenda;

CREATE TABLE IF NOT EXISTS usuario (

    id INTEGER NOT NULL AUTO_INCREMENT,

    nome VARCHAR(60) NOT NULL,

    sobrenome VARCHAR(60) NOT NULL,

    data DATE NOT NULL,

    cep INTEGER(9) NOT NULL,

    opcao VARCHAR(12) NOT NULL,

    email VARCHAR(200) NOT NULL UNIQUE,

    telefone VARCHAR(12) NOT NULL,

    imagem BLOB NOT NULL,

    login VARCHAR(60) NOT NULL UNIQUE,

    senha VARCHAR(60) NOT NULL,

    PRIMARY KEY (id));
